# General tests

In [ ]:
<tf.Tensor: shape=(1, 1, 17, 3), dtype=float32, numpy=
array([[[[0.63281184, 0.49849677, 0.37505552],
         [0.5466186 , 0.57336193, 0.37783977],
         [0.5535949 , 0.40703616, 0.6381436 ],
         [0.5997298 , 0.6592241 , 0.39844656],
         [0.5900171 , 0.29559553, 0.5476833 ],
         [0.87982106, 0.79328775, 0.33499193],
         [0.92426246, 0.24775316, 0.36714965],
         [0.97608685, 0.9277704 , 0.03660851],
         [0.95819116, 0.01209901, 0.00534357],
         [0.86827654, 0.84104306, 0.03206034],
         [0.7733701 , 0.33970886, 0.20269062],
         [0.991373  , 0.63783777, 0.00995263],
         [0.9920549 , 0.25207442, 0.02454685],
         [0.9840312 , 0.80950564, 0.03384359],
         [0.49617958, 0.25371417, 0.02541354],
         [0.9779317 , 0.94460666, 0.02493905],
         [0.8553577 , 0.30861178, 0.00438409]]]], dtype=float32)>

### Get matrix data

In [ ]:
import tensorflow as tf


In [12]:
data = [[[[0.63281184, 0.49849677, 0.37505552],
         [0.5466186 , 0.57336193, 0.37783977],
         [0.5535949 , 0.40703616, 0.6381436 ],
         [0.5997298 , 0.6592241 , 0.39844656],
         [0.5900171 , 0.29559553, 0.5476833 ],
         [0.87982106, 0.79328775, 0.33499193],
         [0.92426246, 0.24775316, 0.36714965],
         [0.97608685, 0.9277704 , 0.03660851],
         [0.95819116, 0.01209901, 0.00534357],
         [0.86827654, 0.84104306, 0.03206034],
         [0.7733701 , 0.33970886, 0.20269062],
         [0.991373  , 0.63783777, 0.00995263],
         [0.9920549 , 0.25207442, 0.02454685],
         [0.9840312 , 0.80950564, 0.03384359],
         [0.49617958, 0.25371417, 0.02541354],
         [0.9779317 , 0.94460666, 0.02493905],
         [0.8553577 , 0.30861178, 0.00438409]]]]
example = tf.constant(data, dtype=tf.float32)



In [ ]:
max_x = tf.reduce_max(example[0][0][:,0])
max_y = tf.reduce_max(example[0][0][:,1])
min_x = tf.reduce_min(example[0][0][:,0])
min_y = tf.reduce_min(example[0][0][:,1])

In [30]:
example[0][0][:,2]

<tf.Tensor: shape=(17,), dtype=float32, numpy=
array([0.37505552, 0.37783977, 0.6381436 , 0.39844656, 0.5476833 ,
       0.33499193, 0.36714965, 0.03660851, 0.00534357, 0.03206034,
       0.20269062, 0.00995263, 0.02454685, 0.03384359, 0.02541354,
       0.02493905, 0.00438409], dtype=float32)>

In [48]:
valid_keypoints[0,:]

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.63281184, 0.49849677, 0.37505552]], dtype=float32)>

In [50]:
example

<tf.Tensor: shape=(1, 1, 17, 3), dtype=float32, numpy=
array([[[[0.63281184, 0.49849677, 0.37505552],
         [0.5466186 , 0.57336193, 0.37783977],
         [0.5535949 , 0.40703616, 0.6381436 ],
         [0.5997298 , 0.6592241 , 0.39844656],
         [0.5900171 , 0.29559553, 0.5476833 ],
         [0.87982106, 0.79328775, 0.33499193],
         [0.92426246, 0.24775316, 0.36714965],
         [0.97608685, 0.9277704 , 0.03660851],
         [0.95819116, 0.01209901, 0.00534357],
         [0.86827654, 0.84104306, 0.03206034],
         [0.7733701 , 0.33970886, 0.20269062],
         [0.991373  , 0.63783777, 0.00995263],
         [0.9920549 , 0.25207442, 0.02454685],
         [0.9840312 , 0.80950564, 0.03384359],
         [0.49617958, 0.25371417, 0.02541354],
         [0.9779317 , 0.94460666, 0.02493905],
         [0.8553577 , 0.30861178, 0.00438409]]]], dtype=float32)>

In [53]:
tf.reshape(valid_keypoints, [8,3])[:,0]

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([0.63281184, 0.5466186 , 0.5535949 , 0.5997298 , 0.5900171 ,
       0.87982106, 0.92426246, 0.7733701 ], dtype=float32)>

In [ ]:
threshold = 0.2
valid_keypoints = tf.reshape(tf.gather(example[0][0], indices=tf.where(example[0][0][:,2]>threshold).numpy(), axis=0), [8,3])
max_x = tf.reduce_max(valid_keypoints[:,0])
max_y = tf.reduce_max(valid_keypoints[:,1])
min_x = tf.reduce_min(valid_keypoints[:,0])
min_y = tf.reduce_min(valid_keypoints[:,1])
print(f"({min_x}, {min_y}), ({max_x}, {max_y})")

bb_area = (max_x-min_x)*(max_y-min_y)
print(bb_area.numpy())

(0.5466185808181763, 0.24775315821170807), (0.9242624640464783, 0.7932877540588379)
0.2060178


In [27]:
tf.reduce_max(example[0][0][:,1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.94460666>

In [ ]:
max_x = max()

In [17]:
example[0][0][:,1]

<tf.Tensor: shape=(17,), dtype=float32, numpy=
array([0.49849677, 0.57336193, 0.40703616, 0.6592241 , 0.29559553,
       0.79328775, 0.24775316, 0.9277704 , 0.01209901, 0.84104306,
       0.33970886, 0.63783777, 0.25207442, 0.80950564, 0.25371417,
       0.94460666, 0.30861178], dtype=float32)>

In [16]:
example[0][0][:,0]

<tf.Tensor: shape=(17,), dtype=float32, numpy=
array([0.63281184, 0.5466186 , 0.5535949 , 0.5997298 , 0.5900171 ,
       0.87982106, 0.92426246, 0.97608685, 0.95819116, 0.86827654,
       0.7733701 , 0.991373  , 0.9920549 , 0.9840312 , 0.49617958,
       0.9779317 , 0.8553577 ], dtype=float32)>